#include <vector>
using namespace std;

class Option {
protected:
	int o[1000];
public:
	Option();
	BOOL LoadOption();
	BOOL SaveOption();
	BOOL CheckOption(vector <int> op, vector <int> nop);
};

// CONST DEFINITION
#define OPTION_ALWAYS			0
#define OPTION_TRUE				0
#define OPTION_SELECT_FOLDER	1
#define OPTION_SELECT_SONG		2
#define OPTION_SELECT_COURSE	3
#define OPTION_SELECT_NEWCOURSE	4
#define OPTION_SELECT_PLAYABLE	5




#define OPTION_DOUBLE			10
#define OPTION_BATTLE			11
#define OPTION_DOUBLEORBATTLE	12
#define OPTION_GHOSTORBATTLE	13






#define OPTION_PANEL_NOTSTART	20
#define OPTION_PANEL_1START		21
#define OPTION_PANEL_2START		22
#define OPTION_PANEL_3START		23
#define OPTION_PANEL_4START		24
#define OPTION_PANEL_5START		25
#define OPTION_PANEL_6START		26
#define OPTION_PANEL_7START		27
#define OPTION_PANEL_8START		28
#define OPTION_PANEL_9START		29
#define OPTION_BGA_NORMAL		30
#define OPTION_BGA_EXTEND		31
#define OPTION_AUTOPLAY_OFF		32
#define OPTION_AUTOPLAY_ON		33
#define OPTION_GHOST_OFF		34
#define OPTION_GHOST_TYPEA		35
#define OPTION_GHOST_TYPEB		36
#define OPTION_GHOST_TYPEC		37
#define OPTION_SCOREGRAPH_OFF	38
#define OPTION_SCOREGRAPH_ON	39
#define OPTION_BGA_OFF			40
#define OPTION_BGA_ON			41

#define OPTION_1P_GROOVE		42
#define OPTION_1P_SURVIVAL		43
#define OPTION_2P_GROOVE		44
#define OPTION_2P_SURVIVAL		45

#define OPTION_OFFLINE			50
#define OPTION_ONLINE			51

#define OPTION_EXTRA_OFF		52
#define OPTION_EXTRA_ON			53

#define OPTION_AUTOSCR_1P_OFF	54
#define OPTION_AUTOSCR_1P_ON	55
#define OPTION_AUTOSCR_2P_OFF	56
#define OPTION_AUTOSCR_2P_ON	57

#define OPTION_SCORE_DISABLE	60
#define OPTION_SCORE_ENABLE		61
#define OPTION_CLEAR_DISABLE	62
#define OPTION_CLEAR_EASY		63
#define OPTION_CLEAR_NORMAL		64
#define OPTION_CLEAR_HARD		65
#define OPTION_FULLCOMBO		66

#define OPTION_LEVEL_BEGINNER	70
#define OPTION_LEVEL_NORMAL		71
#define OPTION_LEVEL_HYPER		72
#define OPTION_LEVEL_ANOTHER	73
#define OPTION_LEVEL_INSANE		74
// 75, 76, 77, 78도 동일하지만 적용 가능한 적당한 메서드를 모르겠음

#define OPTION_LOAD_INCOMPLETE	80
#define OPTION_LOAD_COMPLETE	81

#define OPTION_REPLAY_OFF		82
#define OPTION_REPLAY_RECORD	83
#define OPTION_REPLAY_PLAY		84

// ???
#define OPTION_RESULT_CLEAR		90
#define OPTION_RESULT_MISS		91




/*******************************************************/
/*** FOR SONG SELECT LIST ******************************/
/*******************************************************/
#define OPTION_LIST_NOTPLAYED		100
#define OPTION_LIST_FAILED			101
#define OPTION_LIST_EASYCLEAR		102
#define OPTION_LIST_NORMALCLEAR		103
#define OPTION_LIST_HARDCLEAR		104
#define OPTION_LIST_FULLCOMBO		105

#define OPTION_LIST_AAA				(8.0f/9.0f)
#define OPTION_LIST_AA				(7.0f/9.0f)
#define OPTION_LIST_A				(6.0f/9.0f)
#define OPTION_LIST_B				(5.0f/9.0f)
#define OPTION_LIST_C				(4.0f/9.0f)
#define OPTION_LIST_D				(3.0f/9.0f)
#define OPTION_LIST_E				(2.0f/9.0f)
#define OPTION_LIST_F				(1.0f/9.0f)

#define OPTION_LIST_GUAGE_GROOVE	118
#define OPTION_LIST_GUAGE_SURVIVAL	119
#define OPTION_LIST_GUAGE_SUDDEN	120
#define OPTION_LIST_GUAGE_EASY		121
#define OPTION_LIST_GUAGE_PA		122
#define OPTION_LIST_GUAGE_GA		123

#define OPTION_LIST_OPT_REGULAR		126
#define OPTION_LIST_OPT_MIRROR		127
#define OPTION_LIST_OPT_RANDOM		128
#define OPTION_LIST_OPT_SRANDOM		129
#define OPTION_LIST_OPT_SCATTER		130
#define OPTION_LIST_OPT_CONVERGE	131

#define OPTION_LIST_OPT_HIDDEN		135
#define OPTION_LIST_OPT_SUDDEN		136
#define OPTION_LIST_OPT_HIDSUD		137

#define OPTION_LIST_OPT_AUTOSCR		142
#define OPTION_LIST_OPT_EXTRAMODE	143
#define OPTION_LIST_OPT_DOUBLEBATTLE	144
#define OPTION_LIST_OPT_SPTODP		145

#define OPTION_LIST_DIFF			150
#define OPTION_LIST_DIFF_EASY		151
#define OPTION_LIST_DIFF_NORMAL		152
#define OPTION_LIST_DIFF_HYPER		153
#define OPTION_LIST_DIFF_ANOTHER	154
#define OPTION_LIST_DIFF_INSANE		155

#define OPTION_LIST_7KEY			160
#define OPTION_LIST_5KEY			161
#define OPTION_LIST_14KEY			162
#define OPTION_LIST_10KEY			163
#define OPTION_LIST_9KEY			164

#define OPTION_LIST_BGA_NOTAVILABLE	170
#define OPTION_LIST_BGA_AVILABLE	171
#define OPTION_LIST_NOLONGNOTE		172
#define OPTION_LIST_LONGNOTE		173
#define OPTION_LIST_WITHTEXT		174	//?
#define OPTION_LIST_WITHNOTEXT		175
#define OPTION_LIST_BPM_CHANGE		176
#define OPTION_LIST_BPM_NOCHANGE	177
#define OPTION_LIST_CUSTOMORDER		178
#define OPTION_LIST_NOCUSTOMORDER	179

#define OPTION_LIST_JUDGE_VERYHARD	180
#define OPTION_LIST_JUDGE_HARD		181
#define OPTION_LIST_JUDGE_NORMAL	182
#define OPTION_LIST_JUDGE_EASY		183

#define OPTION_LIST_LEVEL_NORMAL	185 // 레벨 12 이내의 정상치
#define OPTION_LIST_LEVEL_ABNORMAL	186 // 레벨 초과할 경우

#define OPTION_LIST_STAGEFILE_NO	190
#define OPTION_LIST_STAGEFILE_YES	191
#define OPTION_LIST_BANNER_NO		192
#define OPTION_LIST_BANNER_YES		193
#define OPTION_LIST_BACKBMP_NO		194
#define OPTION_LIST_BACKBMP_YES		195
#define OPTION_LIST_PLAY_NO			196
#define OPTION_LIST_PLAY_YES		197


/*******************************************************/
/*** WHILE PLAYING		 *******************************/
/*******************************************************/

#define OPTION_PLAY_1P_AAA			200
#define OPTION_PLAY_1P_AA			201
#define OPTION_PLAY_1P_A			202
#define OPTION_PLAY_1P_B			203
#define OPTION_PLAY_1P_C			204
#define OPTION_PLAY_1P_D			205
#define OPTION_PLAY_1P_E			206
#define OPTION_PLAY_1P_F			207

#define OPTION_PLAY_2P_AAA			210
#define OPTION_PLAY_2P_AA			211
#define OPTION_PLAY_2P_A			212
#define OPTION_PLAY_2P_B			213
#define OPTION_PLAY_2P_C			214
#define OPTION_PLAY_2P_D			215
#define OPTION_PLAY_2P_E			216
#define OPTION_PLAY_2P_F			217

#define OPTION_PLAY_AAA				220	// 확정
#define OPTION_PLAY_AA				221
#define OPTION_PLAY_A				222
#define OPTION_PLAY_B				223
#define OPTION_PLAY_C				224
#define OPTION_PLAY_D				225
#define OPTION_PLAY_E				226
#define OPTION_PLAY_F				227

#define OPTION_PLAY_1P_00PERC		230	// 0~10
#define OPTION_PLAY_1P_10PERC		231 // 10~19
#define OPTION_PLAY_1P_20PERC		232
#define OPTION_PLAY_1P_30PERC		233
#define OPTION_PLAY_1P_40PERC		234
#define OPTION_PLAY_1P_50PERC		235
#define OPTION_PLAY_1P_60PERC		236
#define OPTION_PLAY_1P_70PERC		237
#define OPTION_PLAY_1P_80PERC		238
#define OPTION_PLAY_1P_90PERC		239 // 90~99
#define OPTION_PLAY_1P_100PERC		240 // 100
#define OPTION_PLAY_1P_PERFECT		241
#define OPTION_PLAY_1P_GREAT		242
#define OPTION_PLAY_1P_GOOD			243
#define OPTION_PLAY_1P_BAD			244
#define OPTION_PLAY_1P_POOR			245
#define OPTION_PLAY_1P_AIRPOOR		246	// 공푸어
#define OPTION_PLAY_1P_NOPOORBGA	247
#define OPTION_PLAY_1P_POORBGA		248

#define OPTION_PLAY_2P_00PERC		250	// 0~10
#define OPTION_PLAY_2P_10PERC		251 // 10~19
#define OPTION_PLAY_2P_20PERC		252
#define OPTION_PLAY_2P_30PERC		253
#define OPTION_PLAY_2P_40PERC		254
#define OPTION_PLAY_2P_50PERC		255
#define OPTION_PLAY_2P_60PERC		256
#define OPTION_PLAY_2P_70PERC		257
#define OPTION_PLAY_2P_80PERC		258
#define OPTION_PLAY_2P_90PERC		259 // 90~99
#define OPTION_PLAY_2P_100PERC		260 // 100
#define OPTION_PLAY_2P_PERFECT		261
#define OPTION_PLAY_2P_GREAT		262
#define OPTION_PLAY_2P_GOOD			263
#define OPTION_PLAY_2P_BAD			264
#define OPTION_PLAY_2P_POOR			265
#define OPTION_PLAY_2P_AIRPOOR		266	// 공푸어
#define OPTION_PLAY_2P_NOPOORBGA	267
#define OPTION_PLAY_2P_POORBGA		268

#define OPTION_PLAY_1P_SUDPCHANGE	270
#define OPTION_PLAY_2P_SUDPCHANGE	271

#define OPTION_PLAY_COURSE1			280
#define OPTION_PLAY_COURSE2			281
#define OPTION_PLAY_COURSE3			282
#define OPTION_PLAY_COURSE4			283
#define OPTION_PLAY_COURSE_FINAL	289

#define OPTION_PLAY_COURSE			290
#define OPTION_PLAY_NONSTOP			291
#define OPTION_PLAY_LEVELCOURSE		292	// 단위인정
#define OPTION_PLAY_PROFESSIONAL	293


/*******************************************************/
/*** RESULT				 *******************************/
/*******************************************************/
#define OPTION_RESULT_1P_AAA		300
#define OPTION_RESULT_1P_AA			301
#define OPTION_RESULT_1P_A			302
#define OPTION_RESULT_1P_B			303
#define OPTION_RESULT_1P_C			304
#define OPTION_RESULT_1P_D			305
#define OPTION_RESULT_1P_E			306
#define OPTION_RESULT_1P_F			307

#define OPTION_RESULT_2P_AAA		310
#define OPTION_RESULT_2P_AA			311
#define OPTION_RESULT_2P_A			312
#define OPTION_RESULT_2P_B			313
#define OPTION_RESULT_2P_C			314
#define OPTION_RESULT_2P_D			315
#define OPTION_RESULT_2P_E			316
#define OPTION_RESULT_2P_F			317

#define OPTION_RESULT_BEFORE_AAA	320
#define OPTION_RESULT_BEFORE_AA		321
#define OPTION_RESULT_BEFORE_A		322
#define OPTION_RESULT_BEFORE_B		323
#define OPTION_RESULT_BEFORE_C		324
#define OPTION_RESULT_BEFORE_D		325
#define OPTION_RESULT_BEFORE_E		326
#define OPTION_RESULT_BEFORE_F		327

#define OPTION_RESULT_SCOREUPDATE		330
#define OPTION_RESULT_MAXCOMBOUPDATE	331
#define OPTION_RESULT_MINBPUPDATE		332
#define OPTION_RESULT_TRIALUPDATE		333
#define OPTION_RESULT_RANKINGUPDATE		334
#define OPTION_RESULT_IRUPDATE			334

#define OPTION_RESULT_UPDATE_AAA	340
#define OPTION_RESULT_UPDATE_AA		341
#define OPTION_RESULT_UPDATE_A		342
#define OPTION_RESULT_UPDATE_B		343
#define OPTION_RESULT_UPDATE_C		344
#define OPTION_RESULT_UPDATE_D		345
#define OPTION_RESULT_UPDATE_E		346
#define OPTION_RESULT_UPDATE_F		347

#define OPTION_RESULT_DISABLEFILP	350
#define OPTION_RESULT_FLIPRESULT	351


/*******************************************************/
/*** KEY CONFIG			 *******************************/
/*******************************************************/
#define OPTION_KEY_7OR14KEYS		400
#define OPTION_KEY_9KEYS			401
#define OPTION_KEY_5OR10KEYS		402


/*******************************************************/
/*** OTHERS				 *******************************/
/*******************************************************/
#define OPTION_FOLDER_NOBEGINNER	500
#define OPTION_FOLDER_NONORMAL		501
#define OPTION_FOLDER_NOHYPER		502
#define OPTION_FOLDER_NOANOTHER		503
#define OPTION_FOLDER_NOINSANE		504
#define OPTION_FOLDER_BEGINNER		505
#define OPTION_FOLDER_NORMAL		506
#define OPTION_FOLDER_HYPER			507
#define OPTION_FOLDER_ANOTHER		508
#define OPTION_FOLDER_INSANE		509

#define OPTION_FOLDER_ONEBEGINNER		510
#define OPTION_FOLDER_ONENORMAL			511
#define OPTION_FOLDER_ONEHYPER			512
#define OPTION_FOLDER_ONEANOTHER		513
#define OPTION_FOLDER_ONEINSANE			514
#define OPTION_FOLDER_MULTIBEGINNER		515
#define OPTION_FOLDER_MULTINORMAL		516
#define OPTION_FOLDER_MULTIHYPER		517
#define OPTION_FOLDER_MULTIANOTHER		518
#define OPTION_FOLDER_MULTIINSANE		519

#define OPTION_LEVELBAR_BEGINNER_NOPLAY	520
#define OPTION_LEVELBAR_BEGINNER_FAILED	521
#define OPTION_LEVELBAR_BEGINNER_EASY	522
#define OPTION_LEVELBAR_BEGINNER_CLEAR	523
#define OPTION_LEVELBAR_BEGINNER_HARD	524
#define OPTION_LEVELBAR_BEGINNER_FC		525

#define OPTION_LEVELBAR_NORMAL_NOPLAY	530
#define OPTION_LEVELBAR_NORMAL_FAILED	531
#define OPTION_LEVELBAR_NORMAL_EASY		532
#define OPTION_LEVELBAR_NORMAL_CLEAR	533
#define OPTION_LEVELBAR_NORMAL_HARD		534
#define OPTION_LEVELBAR_NORMAL_FC		535

#define OPTION_LEVELBAR_HYPER_NOPLAY	540
#define OPTION_LEVELBAR_HYPER_FAILED	541
#define OPTION_LEVELBAR_HYPER_EASY		542
#define OPTION_LEVELBAR_HYPER_CLEAR		543
#define OPTION_LEVELBAR_HYPER_HARD		544
#define OPTION_LEVELBAR_HYPER_FC		545

#define OPTION_LEVELBAR_ANOTHER_NOPLAY	550
#define OPTION_LEVELBAR_ANOTHER_FAILED	551
#define OPTION_LEVELBAR_ANOTHER_EASY	552
#define OPTION_LEVELBAR_ANOTHER_CLEAR	553
#define OPTION_LEVELBAR_ANOTHER_HARD	554
#define OPTION_LEVELBAR_ANOTHER_FC		555

#define OPTION_LEVELBAR_INSANE_NOPLAY	560
#define OPTION_LEVELBAR_INSANE_FAILED	561
#define OPTION_LEVELBAR_INSANE_EASY		562
#define OPTION_LEVELBAR_INSANE_CLEAR	563
#define OPTION_LEVELBAR_INSANE_HARD		564
#define OPTION_LEVELBAR_INSANE_FC		565


/*******************************************************/
/*** COURSE				 *******************************/
/*******************************************************/
#define OPTION_COURSE_1COUNT			580
#define OPTION_COURSE_2COUNT			581
#define OPTION_COURSE_3COUNT			582
#define OPTION_COURSE_4COUNT			583
#define OPTION_COURSE_5COUNT			584
#define OPTION_COURSE_6COUNT			585
#define OPTION_COURSE_7COUNT			586
#define OPTION_COURSE_8COUNT			587
#define OPTION_COURSE_9COUNT			588
#define OPTION_COURSE_10COUNT			589

#define OPTION_COURSE_1SELECT			590
#define OPTION_COURSE_2SELECT			591
#define OPTION_COURSE_3SELECT			592
#define OPTION_COURSE_4SELECT			593
#define OPTION_COURSE_5SELECT			594
#define OPTION_COURSE_6SELECT			595
#define OPTION_COURSE_7SELECT			596
#define OPTION_COURSE_8SELECT			597
#define OPTION_COURSE_9SELECT			598
#define OPTION_COURSE_10SELECT			599

#define OPTION_COURSE_SELECTING			571
#define OPTION_COURSE_NOSELECT			572


// 코스 스테이지 1 difficulty 700~799까지. 정확한 사용 값은 모름...


/*******************************************************/
/*** INTERNET RANKING	 *******************************/
/*******************************************************/
#define OPTION_RANKING_NOIR				600
#define OPTION_RANKING_IRLOADING		601
#define OPTION_RANKING_IRLOADCOMPLETE	602
#define OPTION_RANKING_IRNOPLAYER		603
#define OPTION_RANKING_IRCONNECTFAIL	604
#define OPTION_RANKING_IRBAN			605

#define OPTION_RANKING_RANKNOSHOW		620
#define OPTION_RANKING_RANKSHOW			621

#define OPTION_RANKING_NOGHOSTBATTLE	622
#define OPTION_RANKING_GHOSTBATTLE		623

#define OPTION_RANKING_NOCOMPARE		624
#define OPTION_RANKING_COMPARE			625

#define OPTION_RANKING_NOTPLAYED		640
#define OPTION_RANKING_FAILED			641
#define OPTION_RANKING_EASY				642
#define OPTION_RANKING_NORMAL			643
#define OPTION_RANKING_HARD				644
#define OPTION_RANKING_FULLCOMBO		645

#define OPTION_RANKING_AAA				(8.0f/9.0f)
#define OPTION_RANKING_AA				(7.0f/9.0f)
#define OPTION_RANKING_A				(6.0f/9.0f)
#define OPTION_RANKING_B				(5.0f/9.0f)
#define OPTION_RANKING_C				(4.0f/9.0f)
#define OPTION_RANKING_D				(3.0f/9.0f)
#define OPTION_RANKING_E				(2.0f/9.0f)
#define OPTION_RANKING_F				(1.0f/9.0f)


/*******************************************************/
/*** USER CONFIG: 990~998 ******************************/
/*******************************************************/

#define OPTION_FALSE					999	// ALWAYS FALSE